### ISSUE TITLE
Add `cleanup: false` to label without changing the title

### ISSUE THREAD

**Issue by fregante** [fregante/title-to-labels-action#14]
In Refined GitHub we preserve the intro word `Meta:` to tag commits as well as PRs.

This would preserve the title while also adding the label:

```yml
      - uses: fregante/title-to-labels-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          cleanup: false
```
